stages:
  - build

variables:
  FLUTTER_CHANNEL: "stable"
  FLUTTER_VERSION: "2.10.5"

before_script:
  - apt-get update
  - apt-get install -y wget unzip
  - wget https://storage.googleapis.com/flutter_infra_release/releases/$FLUTTER_CHANNEL/linux/flutter_linux_$FLUTTER_VERSION-stable.tar.xz
  - tar xf flutter_linux_$FLUTTER_VERSION-stable.tar.xz
  - export PATH="$PATH:`pwd`/flutter/bin"
  - flutter --version
  - flutter doctor

build_app:
  stage: build
  script:
    - flutter pub get
    - flutter build windows --release --dart-define=DB_HOST=$DB_HOST
  artifacts:
    paths:
      - build/windows/runner/Release/
