stages:
  - setup
  - build
  - deploy
setup:
  stage: setup
  script:
    - powershell -Command "& $env:CI_SCRIPTS_PATH -stage setup"
  tags:
    - kiosk
  only:
    - main
    
build:
  stage: build
  script:
    - powershell -Command "& $env:CI_SCRIPTS_PATH -stage build"
  tags:
    - kiosk
  only:
    - main

deploy:
  stage: deploy
  script:
    - powershell -Command "& $env:CI_SCRIPTS_PATH -stage deploy"
  tags:
    - kiosk-windows
  only:
    - main