before_script:
  - git config --global http.sslVerify false
  - git submodule sync --recursive
  - git submodule update --init --recursive

stages:
  - setup
  - build
  - deploy

setup:
  stage: setup
  script:
    - powershell -Command "& $env:CI_SCRIPTS_PATH -stage setup"
  tags:
    - kiosk-windows

build:
  stage: build
  script:
    - powershell -Command "& $env:CI_SCRIPTS_PATH -stage build"
  tags:
    - kiosk-windows
  artifacts:
    paths:
      - C:\Users\KB\Devcoop\devcoop_self_counter_v1\db_host_log.txt

deploy:
  stage: deploy
  script:
    - powershell -Command "& $env:CI_SCRIPTS_PATH -stage deploy"
  tags:
    - kiosk-windows
  only:
    - main
  artifacts:
    paths:
      - C:\Users\KB\Devcoop\devcoop_self_counter_v1\db_host_log.txt
