stages:
  - analyze
  - build
  - deploy

variables:
  FLUTTER_VERSION: '3.10.0'
  FLUTTER_PATH: 'C:\flutter_temp'
  DEPLOYMENT_PATH: 'C:\DeploymentPath'
  GIT_STRATEGY: fetch

.flutter_setup:
  before_script:
    - |
      $ErrorActionPreference = "Stop"
      if (!(Test-Path $env:FLUTTER_PATH)) {
        New-Item -Path $env:FLUTTER_PATH -ItemType Directory -Force
        Invoke-WebRequest -Uri "https://storage.googleapis.com/flutter_infra_release/releases/stable/windows/flutter_windows_$env:FLUTTER_VERSION-stable.zip" -OutFile "flutter.zip"
        Expand-Archive -Path "flutter.zip" -DestinationPath $env:FLUTTER_PATH -Force
      }
      $env:Path += ";$env:FLUTTER_PATH\flutter\bin"
      flutter doctor
      flutter pub get

analyze:
  extends: .flutter_setup
  stage: analyze
  tags:
    - kiosk
  script:
    - flutter analyze
  allow_failure: true

build:
  extends: .flutter_setup
  stage: build
  tags:
    - kiosk
  script:
    - $buildDir = "build_$($env:CI_PIPELINE_ID)"
    - flutter config --enable-windows-desktop
    - flutter build windows --release --dart-define=DB_HOST=$env:DB_HOST
    - flutter build apk --release --dart-define=DB_HOST=$env:DB_HOST
    - Get-ChildItem -Path build -Recurse # 이 줄을 추가하세요
    - New-Item -ItemType Directory -Force -Path $buildDir
    - Move-Item -Path build\windows\runner\Release\* -Destination $buildDir -Force
  artifacts:
    paths:
      - $buildDir\*
      - build\app\outputs\flutter-apk\app-release.apk
    expire_in: 1 week
  only:
    - main

deploy:
  stage: deploy
  tags:
    - kiosk
  script:
    - powershell -File $env:CI_SCRIPTS_PATH -stage deploy
  only:
    - main
