stages:
  - build
  - test

variables:
  FLUTTER_HOME: "$FLUTTER_HOME"
  PROJECT_PATH: "$PROJECT_PATH"

before_script:
  - export PATH="$FLUTTER_HOME/bin:$PATH"
  - cd "$PROJECT_PATH"
  - flutter --version

build:
  stage: build
  tags:
    - kiosk-windows
  script:
    - flutter clean
    - flutter pub get
    - flutter build apk

test:
  stage: test
  tags:
    - kiosk-windows
  script:
    - flutter test
