stages:
  - setup
  - build
  - deploy

setup:
  stage: setup
  script:
    - 'powershell.exe -File "C:\\Users\\KB\\Devcoop\\ci_script.ps1" -stage setup'
  tags:
    - kiosk-windows

build:
  stage: build
  script:
    - 'powershell.exe -File "C:\\Users\\KB\\Devcoop\\ci_script.ps1" -stage build'
  tags:
    - kiosk-windows

deploy:
  stage: deploy
  script:
    - 'powershell.exe -File "C:\\Users\\KB\\Devcoop\\ci_script.ps1" -stage deploy'
  tags:
    - kiosk-windows
  only:
    - main
