stages:
  - analyze
  - build
  - deploy

variables:
  FLUTTER_VERSION: '3.10.0'
  FLUTTER_PATH: 'C:\flutter_temp'
  DEPLOYMENT_PATH: 'C:\DeploymentPath'

.flutter_setup:
  before_script:
    - |
      $ErrorActionPreference = "Stop"
      if (!(Test-Path $env:FLUTTER_PATH)) {
        New-Item -Path $env:FLUTTER_PATH -ItemType Directory -Force
        Invoke-WebRequest -Uri "https://storage.googleapis.com/flutter_infra_release/releases/stable/windows/flutter_windows_$env:FLUTTER_VERSION-stable.zip" -OutFile "flutter.zip"
        Expand-Archive -Path "flutter.zip" -DestinationPath $env:FLUTTER_PATH -Force
      }
      $env:Path += ";$env:FLUTTER_PATH\flutter\bin"
      flutter doctor
      flutter pub get

analyze:
  extends: .flutter_setup
  stage: analyze
  tags:
    - kiosk
  script:
    - flutter analyze
  allow_failure: true

build:
  extends: .flutter_setup
  stage: build
  tags:
    - kiosk
  script:
    - flutter config --enable-windows-desktop
    - flutter build windows --release --dart-define=DB_HOST=$env:DB_HOST
  artifacts:
    paths:
      - build\windows\x64\runner\Release\*
    expire_in: 1 week
  only:
    - main

deploy:
  stage: deploy
  tags:
    - kiosk
  script:
    - powershell -File $env:CI_SCRIPTS_PATH -stage deploy
  only:
    - main
