stages:
  - setup
  - build
  - deploy

before_script:
  - git config --global http.sslVerify false
  - git submodule sync --recursive
  - git submodule update --init --recursive

setup:
  stage: setup
  script:
    - c:\Users\KB\Devcoop\devcoop_self_counter_v1\ci_script.ps1 -stage setup
  tags:
    - kiosk-windows

build:
  stage: build
  script:
    - c:\Users\KB\Devcoop\devcoop_self_counter_v1\ci_script.ps1 -stage build
  tags:
    - kiosk-windows

deploy:
  stage: deploy
  script:
    - c:\Users\KB\Devcoop\devcoop_self_counter_v1\ci_script.ps1 -stage deploy
  tags:
    - kiosk-windows
  only:
    - main