stages:
  - build
  - deploy

before_script:
  - 'powershell.exe -Command "echo Setting up Flutter environment..."'
  - 'powershell.exe -Command "flutter --version"'

build:
  stage: build
  script:
    - 'powershell.exe -Command "flutter pub get"'
    - 'powershell.exe -Command "flutter build apk --release"'
  artifacts:
    paths:
      - build/app/outputs/flutter-apk/app-release.apk

deploy:
  stage: deploy
  script:
    - 'powershell.exe -Command "echo Deploying the application..."'
    # 배포 스크립트 추가 (예: 앱 스토어 배포, 서버에 업로드 등)
  only:
    - main
