stages:
  - build
  - test

before_script:
  - export PATH="$FLUTTER_HOME/bin:$PATH"
  - cd "$PROJECT_PATH"
  - flutter --version

build:
  stage: build
  script:
    - flutter clean
    - flutter pub get
    - flutter build apk

test:
  stage: test
  script:
    - flutter test