stages:
  - test
  - build
  - deploy

variables:
  FLUTTER_VERSION: '3.10.0'

.flutter_setup:
  before_script:
    - Invoke-WebRequest -Uri "https://storage.googleapis.com/flutter_infra_release/releases/stable/windows/flutter_windows_$FLUTTER_VERSION-stable.zip" -OutFile "flutter.zip"
    - Expand-Archive -Path "flutter.zip" -DestinationPath "C:\"
    - $env:Path += ";C:\flutter\bin"
    - flutter doctor
    - flutter pub get

test:
  extends: .flutter_setup
  stage: test
  tags:
    - kiosk
  script:
    - flutter analyze || true # 분석 결과를 무시하고 계속 진행
    - flutter test

build:
  extends: .flutter_setup
  stage: build
  tags:
    - kiosk
  script:
    - flutter config --enable-windows-desktop
    - flutter build windows --release --dart-define=DB_HOST=$env:DB_HOST
  artifacts:
    paths:
      - build/windows/runner/Release/
    expire_in: 1 week
  only:
    - main

deploy:
  stage: deploy
  tags:
    - kiosk
  script:
    - echo "Deploying application..."
    - powershell -File $env:CI_SCRIPTS_PATH -stage deploy
  only:
    - main
