image: google/dart:latest

stages:
  - test
  - build
  - deploy

variables:
  PUB_CACHE: $CI_PROJECT_DIR/.pub-cache

cache:
  paths:
    - .pub-cache/

before_script:
  - apt-get update -yq
  - apt-get install -y curl git unzip xz-utils zip libglu1-mesa
  - git clone https://github.com/flutter/flutter.git -b stable
  - export PATH="$PATH:`pwd`/flutter/bin"
  - flutter doctor
  - flutter pub get

test:
  stage: test
  script:
    - flutter analyze
    - flutter test

build_windows:
  stage: build
  tags:
    - windows
  script:
    - flutter config --enable-windows-desktop
    - flutter build windows --release --dart-define=DB_HOST=$DB_HOST
  artifacts:
    paths:
      - build/windows/runner/Release/
    expire_in: 1 week
  only:
    - main

deploy:
  stage: deploy
  tags:
    - windows
  script:
    - echo "Deploying application..."
    - powershell -File $CI_SCRIPTS_PATH -stage deploy
  only:
    - main
