image: cirrusci/flutter:2.10.5

stages:
  - build

variables:
  FLUTTER_CHANNEL: "stable"
  FLUTTER_VERSION: "2.10.5"

before_script:
  - flutter --version
  - flutter doctor

build_app:
  stage: build
  script:
    - flutter pub get
    - flutter build windows --release --dart-define=DB_HOST=$DB_HOST
  artifacts:
    paths:
      - build/windows/runner/Release/
