stages:
  - build
  - test

before_script:
  - echo "Setting up Flutter environment"
  - flutter --version

build_app:
  stage: build
  tags:
    - kiosk-windows
  script:
    - echo "Building Flutter App"
    - flutter pub get
    - flutter build apk --release

test_app:
  stage: test
  tags:
    - kiosk-windows
  script:
    - echo "Running Flutter Tests"
    - flutter test

after_script:
  - echo "Cleaning up"
